#
# Create ConfigMap dbloadgen-env for the dbloadgen app
# Data  values are exposed to the dbloadgen container as 
# environment variables.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbloadgen-env
  labels:
    app: dbloadgen
data:
  PASSWORD: admin
  GUIUSER: admin
  PORT: "9090"
  DATASETS: ./datasets
---
#
# Create a pod to run Postgres
#
apiVersion: v1
kind: Pod # Create a pod
metadata:
  name: dbloadgen # Set the name of the pod
  labels:
    app: dbloadgen
spec:
  containers:
    - name: dbloadgen
      image: attunitypm/dbloadgen:latest
      imagePullPolicy: "IfNotPresent"
      tty: true
      stdin: true
      ports:
        - containerPort: 9090 
      envFrom:
        - configMapRef:
            name: dbloadgen-env # Using the ConfigMap dbloadgen-env
  restartPolicy: Never
---
# 
# Create the service that will be used to access Postgres.
#
apiVersion: v1
kind: Service 
metadata:
  name: dbloadgen 
  labels:
    app: dbloadgen 
spec:
  type: NodePort 
  ports:
    - port: 9090 
  selector:
    app: dbloadgen
